services:
  rails:
    from: ruby:2.1.2
    cache:
      - /bundle
    build:
      - apt-get update
      - apt-get install -y libqt4-dev pkg-config
      - apt-get install -y nodejs postgresql-client sqlite3
      - apt-get install -y curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev libxml2-dev libxslt-dev
      - gem install bundler
  postgres: 
    from: postgres
    
test:
  prepare:
    - bundle install --path /bundle
    - bin/rake db:create
  service: rails
  folder: /app
  cmd: "echo '%.......................%'"
  env:
    - RAILS_ENV=test
    - RACK_ENV=test
    - DATABASE_URL=postgres://postgres:mysecretpassword@127.0.0.1:5432/db
